server {
    listen 80;
    server_name space-map.clovis.lol;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name space-map.clovis.lol;

    ssl_certificate /etc/letsencrypt/live/space-map.clovis.lol/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/space-map.clovis.lol/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://backend:8080;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
